### ISSUE TITLE
[Docker] Built image and successfully ran

### ISSUE THREAD

**Issue by SHU-red** [GraphiteEditor/Graphite#2738]
Hi there,
i got graphite production successfully running
- build via dockerfile
- run via docker-compose

Although my implementation may not be the cleanest at the moment i wanted to ask if anyone likes me to contribute my content here?

**Comment by Keavon** [comment]
We don't use Docker in our build tooling, so this would be extraneous and not really something we'd be interested in maintaining or having as file clutter. Hopefully you find it helpful for your own usage though!

**Comment by SHU-red** [comment]
Thank you for your fast and friendly feedback. Seeing that you don`t mind that im using/testing it this way, ill leave the information below for inspiration and use for other people:

I do now have a efficient (GPU accelerated) central instance running on my homeserver
So im not using it for build purposes but for ease of use and accessing a single instance with multiple devices instead of installing the software on each and every device, whereas additionally some devices may be very low end

Thank you for your awesome project
I hope i can use it and contribute in the future


`Dockerfile`
- Build in 2 stages to have a minimal outcome image (build of today has only ca `~70MB`)

```dockerfile
# 1. Builder stage for Rust WASM and frontend build
FROM node:18-bullseye as frontend-builder

# Install Rust toolchain for wasm build
RUN apt-get update && apt-get install -y curl build-essential \
    && curl https://sh.rustup.rs -sSf | sh -s -- -y \
    && export PATH="$HOME/.cargo/bin:$PATH" \
    && rustup target add wasm32-unknown-unknown

ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /usr/local/app

# Clone the repo
RUN git clone https://github.com/GraphiteEditor/Graphite.git

WORKDIR /usr/local/app/Graphite/frontend

# Install npm dependencies
RUN npm install

# Install required cargo tools including cargo-about
RUN cargo install cargo-watch wasm-pack wasm-bindgen-cli cargo-about

# Build production assets (wasm + vite build)
RUN npm run build

# 2. Production stage: serve built assets with nginx
FROM nginx:stable-alpine

# Copy built frontend files from builder stage
COPY --from=frontend-builder /usr/local/app/Graphite/frontend/dist /usr/share/nginx/html

# Expose port
EXPOSE 80

# Start nginx
CMD ["nginx", "-g", "daemon off;"]

```

Build command is
- cd into the directory where Dockerfile is placed
- executing: `docker build -t shur3d/graphite`

`docker-compose` file starts the container, reachable at port `3080`

```yaml
services:
  graphite:
    image: shur3d/graphite:latest
    network_mode: bridge
    container_name: graphite
    privileged: true
    ports:
      - 3080:80
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
